import "./globals.css";


export const metadata = {
  title: "the Car Dealer App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-lightBlue">
        {children}
      </body>
    </html>
  );
}
